name: Playwright Tests
on:
  # TODO: 先設定為僅能手動觸發，等前置的 build action 建置完成後，再增加自動觸發的處理
  workflow_dispatch:
    inputs:
      RUN_ALL_TEST:
        description: '是否跑全部的資料測試'
        required: false
        default: false
        type: boolean

jobs:
  test:
    env:
      RUN_ALL_TEST: ${{ inputs.RUN_ALL_TEST }}

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
